input:
  github-webhook:
    module: input-github-webhook
    port: 9200
    useIndexFromUrlPath: true
    tags:
      - github
      - webhook
      - notification
      
outputFilter: 
  github-logs-format: 
    module: github-logs-format

output: 
  # stdout: yaml
    
  sematext-cloud:
    module: elasticsearch
    url: https://logs-token-receiver.apps.test.sematext.com
    # index: fbe39e0f-34b9-4ee5-981c-5e96b43599e3
    debug: true