input:
  github-webhook:
    module: input-github-webhook
    port: 9200
    tags:
      - github
      - notification
      
output: 
  stdout: yaml
  # http-forwarding:
  #   module: output-http
  #   url: https://event-receiver.apps.test.sematext.com/c2425ff2-5e84-4bf2-b81c-a89564438af7/event