input:
  github-webhook:
    module: input-github-webhook
    port: 9200
    useIndexFromUrlPath: true
    tags:
      - github
      - webhook
      - notification
      
output: 
  # stdout: yaml
  http-forwarding:
    module: output-http
    url: https://event-receiver.apps.test.sematext.com/d111023d-f37c-4ae8-9999-8749d3ad391b/event
  
  
  # add sematext-events-output
  # only use region US or EU and get token from input URL
  # if STE or test env expose `url`
  # have all these values in the webhook input URL and parse them from there

  # the URL should be similar to:
  # webhook.sematext.com/github/<TOKEN>/<REGION>