debug: false

input:
  vercel:
    module: input-vercel
    port: 8400
    useIndexFromUrlPath: true
    clientSecret: <CLIENT_SECRET>
    # workers: 4

      
outputFilter: 
  vercel-format: 
    module: vercel-format

output: 
  # stdout: yaml
    
  sematext-cloud:
    module: elasticsearch
    url: https://logs-token-receiver.apps.test.sematext.com
